version: '3.8'

services:

  mongodb:
    image: mongo:8.0
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser   # Usuario de administrador de MongoDB
      MONGO_INITDB_ROOT_PASSWORD: mypassword # Contraseña de administrador
    ports:
      - "27017:27017"  # Puerto en el que se expone MongoDB
    volumes:
      - mongodata:/data/db  # Volumen persistente para los datos de MongoDB
      - ./init-scripts:/docker-entrypoint-initdb.d  # Scripts de inicialización
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo_express_container
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: myuser  # Usuario para la conexión en mongo-express
      ME_CONFIG_MONGODB_ADMINPASSWORD: mypassword  # Contraseña para la conexión
      ME_CONFIG_MONGODB_SERVER: mongodb  # Host de MongoDB (nombre del servicio)
    ports:
      - "8081:8081"  # Exponer mongo-express en el puerto 8081
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodata:
    driver: local

# mongodb://myuser:mypassword@localhost:27017
# mongodb://myuser:mypassword@mongodb:27017
